"""harvest/06_export_licences.py — LICENCES.md, generated, never hand-written.

TEAM-CHARTER non-negotiable #7: LICENCES.md is built from manifest.jsonl, so
attribution can never silently drift from the assets actually shipped. Every row
becomes a credit line grouped by licence.

Stdlib only.

    python harvest/06_export_licences.py
    python harvest/06_export_licences.py --out ../LICENCES.md
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from common import HARVEST_DIR, load_manifest

DEFAULT_OUT = HARVEST_DIR.parent / "LICENCES.md"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    rows = load_manifest()
    shipped = [r for r in rows if r.get("extra", {}).get("keep") is not False]

    by_licence: dict[str, list[dict]] = defaultdict(list)
    for r in shipped:
        by_licence[r.get("licence", "unknown")].append(r)

    lines = [
        "# Licences & attribution",
        "",
        "> Generated by `harvest/06_export_licences.py` from `harvest/manifest.jsonl`.",
        "> Do not edit by hand (TEAM-CHARTER #7). Re-run after every harvest.",
        "",
        f"{len(shipped)} assets across {len(by_licence)} licence(s).",
        "",
    ]

    for licence in sorted(by_licence):
        items = by_licence[licence]
        lines.append(f"## {licence} ({len(items)})")
        lines.append("")
        for r in sorted(items, key=lambda x: x.get("source", "")):
            author = r.get("author") or "unknown"
            title = r.get("title") or r.get("id")
            url = r.get("url", "")
            src = r.get("source", "")
            lines.append(f"- **{title}** — {author} · {src} · <{url}>")
        lines.append("")

    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out} — {len(shipped)} assets, {len(by_licence)} licences")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
