import { StyleSheet, View } from 'react-native';

import { Button, Text } from '@/components/ui';
import { useNarration } from '@/hooks';
import { spacing } from '@/theme';

export type NarrationPlayerProps = {
  /** The site whose narration to load. */
  siteId?: string | null;
  /** Start playing as soon as this site becomes the current one. */
  autoPlay?: boolean;
  /** Drop the narration text and show only the transport, where the passage is already on screen. */
  textless?: boolean;
};

/**
 * The recorded narration, with its text.
 *
 * All of the behaviour lives in `useNarration` so the site detail screen and
 * the arrival sheet cannot drift apart — the arrival sheet is where narration
 * starts by itself, and a second implementation there is exactly where an
 * automatic voice would end up with different stop conditions from the manual
 * one.
 */
export function NarrationPlayer({ siteId, autoPlay = false, textless = false }: NarrationPlayerProps) {
  const { hasAudio, narration, playing, positionSeconds, durationSeconds, toggle } = useNarration(
    siteId,
    { autoPlay },
  );

  if (!narration && !hasAudio) return null;

  return (
    <View style={styles.card}>
      <Text variant="heading">Narration</Text>

      {narration && !textless ? (
        <Text variant="body" tone="secondary" style={styles.narrationText}>
          {narration.en}
        </Text>
      ) : null}

      {hasAudio ? (
        <View style={styles.controls}>
          <Button
            label={playing ? 'Pause' : 'Listen'}
            variant="secondary"
            onPress={toggle}
            accessibilityHint="Plays the recorded narration for this place"
          />
          <Text variant="caption" tone="muted">
            {positionSeconds > 0 || playing
              ? `${positionSeconds}s / ${durationSeconds}s`
              : `~${durationSeconds}s`}
          </Text>
        </View>
      ) : (
        // Said rather than left blank. The recordings are generated by a
        // PowerShell script, so a missing one is an ordinary state of the repo
        // on most machines, not a fault on this device.
        <Text variant="caption" tone="muted">
          No recording for this place yet — the text above is the narration.
        </Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  narrationText: {
    fontStyle: 'italic',
    lineHeight: 22,
  },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
  },
});
