import narrationData from '../seed/narration.json';

/**
 * Narration audio.
 *
 * The twelve `.opus` files are generated by `tools/make-narration-audio.ps1`.
 * They must be committed, not gitignored: Metro resolves `require()` at bundle
 * time, so a static require of an untracked file is not a missing asset at
 * runtime — it is a bundling failure, and `Unable to resolve module
 * ../assets/audio/ashokan-pillar.en.opus` broke the app for everyone who had
 * not run the generator locally.
 *
 * The twelve `.opus` files are generated by `tools/make-narration-audio.ps1`
 * and were gitignored as build output. But Metro resolves `require()` at bundle
 * time, so a static require of an untracked file is not a missing asset at
 * runtime — it is a *bundling* failure. `Unable to resolve module
 * ../assets/audio/ashokan-pillar.en.opus` broke the app for everyone except the
 * machine that had run the generator, and that generator is PowerShell, so in
 * practice everyone not on Windows.
 *
 * An asset the bundler requires statically has to be in the repository. When
 * real narration is recorded, commit the files to `assets/audio/` — they are no
 * longer ignored — and register them in `siteAudioFiles` below. Until then
 * `audioForSite` returns undefined, `NarrationPlayer` renders the narration
 * text without transport controls, and nothing breaks.
 *
 * The text is unaffected: it lives in `seed/narration.json`, which is tracked.
 */

/**
 * Site id → bundled audio module.
 *
 * Written out rather than derived: Metro resolves `require()` at bundle time
 * and needs a literal path, so a loop over a filename list would resolve
 * nothing. Adding a site means adding a line here *and* committing the file.
 */
export const siteAudioFiles: Record<string, number> = {
  'ashokan-pillar': require('../assets/audio/ashokan-pillar.en.opus'),
  'china-temple': require('../assets/audio/china-temple.en.opus'),
  'gautami-nuns-temple': require('../assets/audio/gautami-nuns-temple.en.opus'),
  'korean-temple': require('../assets/audio/korean-temple.en.opus'),
  'marker-stone': require('../assets/audio/marker-stone.en.opus'),
  'maya-devi-temple': require('../assets/audio/maya-devi-temple.en.opus'),
  'myanmar-temple': require('../assets/audio/myanmar-temple.en.opus'),
  'puskarini': require('../assets/audio/puskarini.en.opus'),
  'ramagrama': require('../assets/audio/ramagrama.en.opus'),
  'tilaurakot': require('../assets/audio/tilaurakot.en.opus'),
  'vihara-remains': require('../assets/audio/vihara-remains.en.opus'),
  'world-peace-pagoda': require('../assets/audio/world-peace-pagoda.en.opus'),
};

export type NarrationEntry = {
  site_id: string;
  approx_seconds: number;
  ne_review: string;
  en: string;
  ne: string;
};

export const narrations: NarrationEntry[] = narrationData;

/** Narration audio for a site, when the file is bundled. */
export function audioForSite(siteId: string): number | undefined {
  return siteAudioFiles[siteId];
}

/** Narration text for a site. Always available — it ships in the seed. */
export function narrationForSite(siteId: string): NarrationEntry | undefined {
  return narrations.find((item) => item.site_id === siteId);
}

/**
 * Sites whose narration text exists but whose audio does not.
 *
 * Diagnostic rather than decorative: it is the number that tells you whether
 * the generator has been run and its output committed.
 */
export function sitesMissingAudio(): string[] {
  return narrations.map((n) => n.site_id).filter((id) => !siteAudioFiles[id]);
}
